### ISSUE TITLE
change repo description

### ISSUE THREAD

**Issue by runcom** [projectatomic/skopeo#10]
Repository description isn't accurate anymore since skopeo is about to be able to download image's layers in addition to inspect images on a repository

**Comment by rhatdan** [comment]
Yes lets rewrite this to skopeo is a mechanism to work with remote registries including retrieving information, images, signing content.

**Comment by runcom** [comment]
Problem is I can edit that, probably Jhon can

**Comment by runcom** [comment]
seems like I gathered sufficient privileges to edit it, I'll to it asap
