### ISSUE TITLE
[RFE] docker client - do not read $HOME/.docker/config.json

### ISSUE THREAD

**Issue by runcom** [projectatomic/skopeo#106]
it's ugly that a library is retrieving credentials from something on the host w/o users noticing. I think we should find a way to abstract credentials and put them directly on ImageSource initialization

**Comment by mtrmac** [comment]
Hum, but the default implementation should still read that file (or whatever `docker login` sets up), right?

Equally, it would be nice to have a reliable way to run in-process unit tests which do not touch the home directory.

I am currently looking at how `parseImage…` get their `certPath` and `tlsVerify` parameters, which is ugly to pass down into `ImageSource`. I guess we would benefit from a `SystemContext` / `OuterWorldConfiguration` / `HereYouCanAskAboutYourEnvironment` (all silly names, I know, there must be a better one) structure to create per-process and to pass to the `ImageSource`/`ImageDestination` constructors.

**Comment by runcom** [comment]
> SystemContext

+1000
