### ISSUE TITLE
manifests handling

### ISSUE THREAD

**Issue by runcom** [projectatomic/skopeo#109]
@mtrmac we need something like https://godoc.org/github.com/docker/distribution/manifest and https://godoc.org/github.com/docker/distribution#RegisterManifestSchema.

https://github.com/docker/distribution/blob/master/manifests.go#L86

This should play well with the `manifest` interface also. We really need to abstract manifests code in skopeo.

I think their structure is perfect in our case when dealing with different kind of manifests media types (and marshaling/unmarshaling)

WDYT I can work on this after #102 and #103

**Comment by runcom** [comment]
https://github.com/docker/distribution/blob/master/manifests.go#L13 this is what out interfaces would look like as well - and it's easy to work with this -> https://github.com/docker/distribution/blob/master/registry/client/repository.go#L493

**Comment by mtrmac** [comment]
Revisiting this, in light of `containers/image/image.genericManifest`, is there still anything else to do here?

**Comment by runcom** [comment]
Maybe not

**Comment by mtrmac** [comment]
> Revisiting this, in light of `containers/image/image.genericManifest`, is there still anything else to do here?

> Maybe not

Closing, then. (If more manifest handling API were needed, that should be tracked in `containers/image` anyway.)
