### ISSUE TITLE
Decide how to reuse the demo shell script

### ISSUE THREAD

**Issue by mtrmac** [projectatomic/skopeo#119]
A recent demo of the signing functionality is fairly easy to reuse / explain.  Within `skopeo`, we will replace it with Go code in #118, so there is no reason to keep it in the git repo right now, but it seems a pity to just throw it away.

The shell script still might be useful as is, perhaps as a part of an introduction/walkthrough documentation in the repository, or as a blog post.

So, I will attach the shell script to this issue.  Note that it requires the full `--sign-by` and `--policy` functionality and the fixtures from #118 (~per my current integrate-all-the-things branch), and it is designed to run inside the `skopeo-dev` container built by `Makefile`.

In the worst case, this issue can be closed (perhaps even immediately) and the attached shell script will be preserved in the issue.
[start-openshift.sh.txt](https://github.com/projectatomic/skopeo/files/328100/start-openshift.sh.txt)

**Comment by runcom** [comment]
> The shell script still might be useful as is, perhaps as a part of an introduction/walkthrough documentation in the repository, or as a blog post.

this can be a doc RFE and will leave this open

**Comment by mtrmac** [comment]
We now have #320 , which automates parts of this shell script, and the demo uses in there are probably bitrotten by now.
