### ISSUE TITLE
Support openshift 'oc login'

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/skopeo#152]
The capability to use .kubeconfig files is great but we frequently don't have the oc client installed on the system to manage the .kubeconfig file.

This is a request for skopeo to support this so we can reduce the host dependencies.

**Comment by aweiteka** [comment]
cc @rhatdan

**Comment by runcom** [comment]
+1

**Comment by rhatdan** [comment]
Lets create a trello card for this.

**Comment by runcom** [comment]
@aweiteka what's the plan here? What is actually missing/required to do?

**Comment by aweiteka** [comment]
> Lets create a trello card for this.

https://trello.com/c/92MhH2YF

**Comment by aweiteka** [comment]
Related issue https://github.com/containers/image/issues/188

**Comment by mtrmac** [comment]
As of #322, and OpenShift 1.5, `oc login` is no longer needed for using signatures; instead, the `docker:` transport can be used (after only `docker login`) to access signed images.

Given that, is a `skopeo` variant of `oc login` still needed?

**Comment by aweiteka** [comment]
> Given that, is a skopeo variant of oc login still needed?

No, I don't think so. Closing.
