### ISSUE TITLE
Add optional sigstore URI to policy format

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/skopeo#164]
In many cases, signatures are served from a different server than the registry. We need a way to map this signature server (sigstore?) to a registry.

**Comment by mtrmac** [comment]
As mentioned elsewhere, I am thinking of this as conceptually a transport-specific per-server configuration item (like Docker’s `--insecure-registry`, or configuring a proxy or a local mirror for a public server), not a matter of how to verify signatures.

We do need a way to do such transport-specific per-server configuration, if only to share `--insecure-registry` configuration between docker and atomic and skopeo.

**Comment by mtrmac** [comment]
This has been implemented in #170, not in policy but in https://github.com/containers/image/blob/master/docs/registries.d.md .
