### ISSUE TITLE
New transport type: localdocker://

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/skopeo#167]
We want to be able to build an image then use skopeo copy to sign and push to a registry. For example:

```
docker build foo/bar
skopeo copy --sign-by me@example.com localdocker://foo/bar docker://reg.example.com/foo/bar
```

cc @baude

**Comment by mtrmac** [comment]
(Should be implemented in https://github.com/containers/image and require no support directly in skopeo.)

**Comment by aweiteka** [comment]
Moved to https://github.com/containers/image/issues/53
