### ISSUE TITLE
Create DBUS API for Python, etc

### ISSUE THREAD

**Issue by baude** [projectatomic/skopeo#172]
As of now, the Atomic CLI must use a subprocess to interact with skopeo.  This is not entirely ideal.  Among other things, you can see type differences between python2 and 3 when working with the returned information.

DBUS would allow us to "bind" with subprocess, define return types, etc.

**Comment by mtrmac** [comment]
> Among other things, you can see type differences between python2 and 3 when working with the returned information.

What does this mean precisely?

> DBUS would allow us to "bind" with subprocess, define return types, etc.

To the extent `skopeo` is being used as an ordinary library, moving it to D-Bus will run it under a separate user account, likely having to be `root` to make various operations possible, which is… pretty awkward. I’m sure that there is a secure way to implement `skopeo copy $something dir:$arbitrarypath` as a D-Bus service but I’d very much enjoy if we didn’t have to figure it out :)

ATM the information returned by `skopeo` is pretty light on types; there is optional log output, there is untyped raw data (`inspect --raw`), and, yes, there is JSON (`inspect`). 

I’m not saying there couldn’t possibly be a benefit, but the cost/benefit ratio is unclear to me.

And sure, using a single language and just function calls is much better than either subprocesses or D-Bus. Which is more or less the reason why `skopeo` was created separate from `atomic`, to take advantage of existing the Golang ecosystem.

**Comment by mtrmac** [comment]
> To the extent skopeo is being used as an ordinary library, moving it to D-Bus will run it under a separate user account, likely having to be root to make various operations possible, which is… pretty awkward.

I guess we could do the systemd thing, and use the D-Bus message passing protocol on a private pipe without touching the bus at all. I’m not sure that this is an improvement over formatting and parsing JSON; it might be, OTOH D-Bus doesn’t map into Python types quite precisely either (IIRC something about typed empty arrays).

[/me yearns for a single well-integrated IPC mechanism and cross-language marshaling mechanism integrated throughout the Linux ecosystem…]

**Comment by baude** [comment]
Using subprocesses in python2 and python3, you will see python3 return things as bytes and python2 as strings as a simple example.

I understand your user concerns. It is valid.  The question probably becomes whether the benefit is worth it.  And yes, a well-integrated IPC would be nice :)

**Comment by runcom** [comment]
> Using subprocesses in python2 and python3, you will see python3 return things as bytes and python2 as strings as a simple example.

This really seems something outside the scope of skopeo itself - also, while I would have loved a well-integrated IPC, even D-BUS, that really seems a lot of work when instead we could add more strong parsing on subprocess return(s) in both python versions.

@baude am I missing something saying that it can be up to atomic to have a stronger parsing around subprocess returns?

**Comment by baude** [comment]
The problem with the parsing is that it is sensitive to changes made in skopeo.  So if you change, we have to understand that change and change as well.  I suppose that can be the case for many methods, etc.  Something like dbus just provides a cleaner method of interaction and avoids subprocess calls.

Do you ever anticipate other things like cockpit interacting with your code?

**Comment by runcom** [comment]
Nope we don't have such plans now (cockpit+skopeo)

**Comment by rhatdan** [comment]
cockpit will interact with atomic not directly with skopeo

**Comment by mtrmac** [comment]
> The problem with the parsing is that it is sensitive to changes made in skopeo. So if you change, we have to understand that change and change as well.

That’s exactly the same with D-Bus; if we screw up and change the interface, or keep the interface but change its semantics, it doesn’t really matter whether we break `atomic` by changing the JSON output format or by changing the D-Bus method signature.

**Comment by runcom** [comment]
+1 @mtrmac, that what I was thinking as well

**Comment by lcarva** [comment]
How about generating C bindings? I'm not saying it's perfect, just posting an alternative: https://medium.com/learning-the-go-programming-language/calling-go-functions-from-other-languages-4c7d8bcc69bf

**Comment by rhatdan** [comment]
Now that podman has a Varlink API you can do a lot of what people use skopeo for via podman

podman pull. podman push  Can all be done via varlink which as an API for Python, C and Javascript among others.

**Comment by mtrmac** [comment]
If any C bindings were created, they would be for containers/image, not for skopeo. But I can’t see that it would help with any of the features underlying this request: It would require a C consumer, just like the existing c/image requires a Go consumer — i.e. not language-neutral; and it would not help at all with API stability.

The podman varlink API is indeed a good alternative, notably also because it avoids the daemon and the privilege escalation risks; every application can run a podman varlink server within its own privilege context.

**Comment by lcarva** [comment]
> not language-neutral;

C bindings work for various languages, not just C: python, ruby, node, and Java.

[Varlink API](https://varlink.org/) does look like a better option though.

**Comment by rhatdan** [comment]
Closing this issue.

**Comment by ktdreyer** [comment]
I'm interested in querying the labels for a particular image tagged in a registry, using Python.

Is there a way to use "skopeo inspect" in Python to do this?

Or should I use https://pypi.org/project/python-dxf/ ?

**Comment by rhatdan** [comment]
You would have to exec skopeo from python,  We don't have python bindings yet for containers image, although theoretically they would be possible.
