### ISSUE TITLE
Do not hard code registry port

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/skopeo#189]
As a registry admin I am able to configure the registry to serve on any port. When using a port other than 5000 I get this error:

        "Invalid format of docker reference: expecting port 5000"

See https://github.com/projectatomic/skopeo/blob/4421e7ea2face14ce4530ed6e6df66b6f94d544f/vendor/github.com/containers/image/openshift/openshift.go#L164

Could we discover the port using `~/.docker/config.json`?

**Comment by mtrmac** [comment]
Philosophically, no, `config.json` could contain different registries for the same host, differentiated by a port.

Really what we need here is a way to get the official endpoint from the OpenShift API server, as https://github.com/projectatomic/skopeo/blob/4421e7ea2face14ce4530ed6e6df66b6f94d544f/vendor/github.com/containers/image/openshift/openshift.go#L164 says. Is that still not possible?

**Comment by mtrmac** [comment]
> Philosophically, no, `config.json`

(Of course this means “in practice, yes”, but I’d much prefer a real solution to this, ingenious but ultimately risky and ugly workaround. Especially if the hostname ends up being one of the few public IPs of a cluster, this could easily collide with someone’s private registry exposed on the same IP address, couldn’t it?)

**Comment by aweiteka** [comment]
> Really what we need here is a way to get the official endpoint from the OpenShift API server ... Is that still not possible?

Sadly, no. See https://github.com/openshift/origin/issues/2162

> Especially if the hostname ends up being one of the few public IPs of a cluster, this could easily collide with someone’s private registry exposed on the same IP address, couldn’t it?

Yes. Good point.
