### ISSUE TITLE
Rename "policy" to "trust"

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/skopeo#191]
The word "trust" seems to resonate with docker users. See [Docker Content Trust](https://github.com/docker/notary/tree/master/docs). The skopeo policy file describes trust quite well but its use must be translated for the uninitiated.

I'm not suggesting we do a global search and replace, but in cases where users interact with files or output, "trust" is a better term to use IMO. Specifically, these files:

cmd/skopeo/copy.go
cmd/skopeo/main.go
docs/skopeo.1.md
Makefile

cc @rhatdan

**Comment by rhatdan** [comment]
Make sense to me.

**Comment by runcom** [comment]
+1

**Comment by rhatdan** [comment]
https://github.com/projectatomic/skopeo/pull/192
