### ISSUE TITLE
Add signing metadata during push to API

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/skopeo#193]
The OpenShift API [ImageSignature object](https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-imagesignature) provides storage for useful metadata. Skopeo should write this data if possible.
- imageIdentity: <image_reference>
- created: <timestamp>
- issuedBy: <email>
- issuedTo: <email> # what's the difference?

To clarify to the end user that this information is not verified, populate the [SignatureCondition object](https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-signaturecondition) with the following fields:
- type: "Complete"
- status: "Unknown"
- lastProbeTime: <timestamp>
- reason: "Initial signing request"
- message: <???>

**Comment by aweiteka** [comment]
cc @stefwalter

**Comment by mtrmac** [comment]
AFAIK OpenShift explicitly prohibits updating these fields, per https://github.com/openshift/origin/pull/9181/files#diff-338f8de5c2e444ebed64ed7ac61109e4R111 and https://github.com/openshift/origin/pull/8371/files#diff-338f8de5c2e444ebed64ed7ac61109e4R101 . So at the moment there is nothing for skopeo to do. (The original design was that OpenShift would populate these fields from the received blob. We can of course change/renegotiate that. Just clarifying that this won’t happen this week.)

(
- `issuedBy` is ~nonsense (it says which CA signed the key)
- `issuedTo` = the key owner

)

**Comment by aweiteka** [comment]
> The original design was that OpenShift would populate these fields from the received blob

That's disappointing. The data isn't in the blob! So we cannot POST any arbitrarily data to the ImageSignature object?

**Comment by mtrmac** [comment]
`imageIdentity` is in the blob directly; for `issuedTo` the blob gives us the fingerprint but not the real name.  `issuedBy` doesn’t have clear semantics with GPG, and is not in the blob. The verification status data of course isn’t in the blob.

**Comment by mtrmac** [comment]
@aweiteka Given https://github.com/openshift/origin/pull/13585 , is (some variant of) this still necessary?

**Comment by aweiteka** [comment]
> Given openshift/origin#13585 , is (some variant of) this still necessary?

No. Closing.
