### ISSUE TITLE
create new release

### ISSUE THREAD

**Issue by dustymabe** [projectatomic/skopeo#197]
it's been a while since the last release of this was put out. Can we cut a tag and so that a distro (like Fedora) can ship an updated version?

**Comment by runcom** [comment]
We should, we just went ahead and rebuilt using a new commit (but same version). I'll tag asap and rebuild for Fedora at least.

**Comment by dustymabe** [comment]
looks like the latest version in Fedora is `0.1.14-3.gitd830391.fc24`. Can we get this updated ?

As a side note I don't see `0.1.14` listed as an actual release: https://github.com/projectatomic/skopeo/releases
