### ISSUE TITLE
warn when encountering old unsupported image format 

### ISSUE THREAD

**Issue by dustymabe** [projectatomic/skopeo#198]
When trying to download an old style docker v1 image format I get an error:

```
$ ./skopeo copy docker://dustymabe/fedora20-pdftk:latest oci:fedorapdftk 
FATA[0010] Error writing manifest: Unrecognized manifest media type
```

talking with @runcom I was able to find out that the image format was old and I needed to point to newer v2 images in order to get it to work. would be great if we could add a helpful message for our users on this point.

**Comment by mtrmac** [comment]
The offending code is actually in https://github.com/containers/image . 

Two points:
- The error message should include the MIME type. That would allow…
- … figuring out what is going on. The code is already supposed to fail with a bit nicer error messages (e. g. `can't create OCI manifest from Docker V2 schema 1 manifest`). This error message says that we don’t recognize it at all.
- (And eventually we should just be able to convert from the old format; that is hopefully coming but not really a fix to the particular reported problem.)

**Comment by dustymabe** [comment]
> The offending code is actually in https://github.com/containers/image .

@mtrmac - are you saying the bug isn't in skopeo? 

FYI - just for the record the commit of skopeo I was using at the time was 362bfc5fe37db08b945d190c377b617c6a7e4c3c

**Comment by mtrmac** [comment]
> @mtrmac - are you saying the bug isn't in skopeo? 

Yes, `skopeo copy` is just https://github.com/projectatomic/skopeo/blob/master/cmd/skopeo/copy.go ; all work actually happens in the other repo.  Roughly the same people are maintaining both, so it doesn’t matter that much, only if someone wanted to help debugging (https://github.com/containers/image/blob/master/oci/layout/oci_dest.go#L136 )

**Comment by dustymabe** [comment]
thanks, i'll try to submit future copy issues against containers/image

**Comment by runcom** [comment]
see https://github.com/containers/image/pull/83

**Comment by mtrmac** [comment]
https://github.com/containers/image/issues/83 adds a generic diagnostic, is that sufficient to fix this issue? From https://github.com/containers/image/issues/83 it seemed that we should add the “signed schema1” type to the `switch`.

**Comment by runcom** [comment]
> containers/image#83 adds a generic diagnostic, is that sufficient to fix this issue? From containers/image#83 it seemed that we should add the “signed schema1” type to the switch.

@mtrmac 
the switch is meant for schemas where I suppose one day will be "convertible" to OCI v1 (I think it's just work to do)
signed schema1 isn't compatible at all and cannot be converted

**Comment by runcom** [comment]
reopening till containers/image#83 is vendored here

**Comment by mtrmac** [comment]
Sure, this will not make it _work_, but we already have a nicer “schema 1 is not supported” error message in that `switch`; if the underlying cause of the failure is that we have detected schema 1, it would be nice to use this more specific error message instead of “unrecognized MIME type”.
