### ISSUE TITLE
Does skopeo support pushing / pulling OCI images to / from private registries?

### ISSUE THREAD

**Issue by lizhuqi** [projectatomic/skopeo#206]

**Comment by amitsaha** [comment]
No, it doesn't yet.

**Comment by ryansanford** [comment]
Is support for this planned?

**Comment by rhatdan** [comment]
If you are asking if this is supported on RHEL, then the answer is yes.

**Comment by runcom** [comment]
There's no current support for pulling/pulling OCI images to registry *at all*. There's no capable container registry out there yet. docker/distribution might add this though (no eta).

**Comment by rhatdan** [comment]
@ryansanford I guess I misspoke.  Skopeo is fully supported on RHEL. This feature needs support on the Registry level. We have pull requests into upstream docker-distribution project, but they are probably going to wait until OCI 1.0 is declared.

@vbatts Do you have any idea how this is going?

**Comment by ryansanford** [comment]
Let me be more specific. I'd like to use skopeo to interact with a private repository on dockerhub.

**Comment by runcom** [comment]
> Let me be more specific. I'd like to use skopeo to interact with a private repository on dockerhub.

That's supported (there's no OCI in dockerhub...).

**Comment by ryansanford** [comment]
@runcom 
Your response forced me to recheck our private repos, which could be inspected, versus our private ones, which could not be inspected. What I found is that our private repos aren't utilizing the `latest` tag, and as soon as I added one, `skopeo inspect` is now working as expected with that private repo.

Thank you so much for this great tool! The lack of command-line tools for interacting with dockerhub private repos has been a pain point for a while.

**Comment by runcom** [comment]
> @runcom
> Your response forced me to recheck our private repos, which could be inspected, versus our private ones, which could not be inspected. What I found is that our private repos aren't utilizing the latest tag, and as soon as I added one, skopeo inspect is now working as expected with that private repo.
> 
> Thank you so much for this great tool! The lack of command-line tools for interacting with dockerhub private repos has been a pain point for a while.

Thanks a lot for supporting @ryansanford! - we aim at building other open source tools for many other stuff going on with containers. Would be nice to spread the work out that tools like this are indeed needed by the community!
