### ISSUE TITLE
Specify user's gpg keyring for signing

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/skopeo#207]
As I understand it, skopeo uses the current user's keyring for signing. When the tool is run using `sudo` this means the available signing keys are not mine but root's. As a user this is unexpected. I want to be able to use my private keys to sign, not root user's keys.

**Proposal:**

1. By default use the caller's keyring using a command like this:

        sudo gpg2 --list-keys --homedir $(eval echo ~$(who am i | awk '{print $1}'))/.gnupg
1. Add a `--keyringuser USERNAME` option to override default keyring lookup.

**Comment by aweiteka** [comment]
cc @ddarrah

**Comment by runcom** [comment]
> Add a --keyringuser USERNAME option to override default keyring lookup.

I'm all for this one - proposal 1) is tricky (and we had hassles in docker/docker when playing with sudo and the user's home dir)

**Comment by mtrmac** [comment]
Does setting `$GNUPGHOME` work? The tests use that, so it should.

(Not saying that this is an optimal interface, just that there is a clumsy option right now.)

**Comment by mtrmac** [comment]
As a bigger hammer, `sudo -E` instead of plain `sudo`; though that may have unforeseen effects (root-owned files written into users’ home and the like.)

**Comment by rhatdan** [comment]
--homedir $(eval echo ~$SUDO_USER)

**Comment by rhatdan** [comment]
Actually just doing
sudo gpg2 --list-keys --homedir ~/.gnupg

Works

**Comment by aweiteka** [comment]
Resolved by https://github.com/projectatomic/atomic/pull/643
