### ISSUE TITLE
Create imagestream during oc copy

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/skopeo#208]
With `atomic:` transport type destination we need skopeo to create an empty imagestream during copy workflow. During docker push to the openshift registry this occurs automatically. This is  a request to match the docker push workflow.

API docs: https://docs.openshift.org/latest/rest_api/openshift_v1.html#create-a-imagestream

**Comment by aweiteka** [comment]
@runcom would it be possible to get this in? The alternative means an awkward extra command `oc create is STREAM`.

**Comment by mtrmac** [comment]
i.e. something like https://github.com/openshift/origin/blob/master/pkg/dockerregistry/server/repositorymiddleware.go#L399 I guess

**Comment by aweiteka** [comment]
@mtrmac is this PR a dependency for this?  https://github.com/containers/image/pull/95

**Comment by mtrmac** [comment]
Not a dependency; a supposed fix. Care to test today’s integrate-all-the-things?

**Comment by aweiteka** [comment]
@baude FYI.
