### ISSUE TITLE
"atomic" type needs registries.d config

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/skopeo#209]
Use case: As an unauthenticated user I am able to pull images from Openshift-based Atomic Registry. We cannot depend on ~/.kube/config current context since the user may not be authenticated. Therefore we have no reference for getting the OpenShift API endpoint.

```
atomic:
 registry.example.com:
  sigstore: api.example.com:8443
```

**Comment by ddarrah** [comment]
What about something like 'atomic trust add-registry --integrated true --sigstore api.example.com registry.example.com'?  For a lookaside it could be 'atomic trust add-registry --integrated false --sigstore http://sigstore.example.com registry.example.com'.

**Comment by mtrmac** [comment]
Sure, supporting non-default clusters would be great. How do we get an API token without `~/.kube/config` though?

**Comment by aweiteka** [comment]
> How do we get an API token without ~/.kube/config though?

If you're pulling as an unauthenticated user you don't have a token. In other words, you're hitting both the docker API and openshift API unauthenticated.

**Comment by mtrmac** [comment]
BTW this could be automatic and configuration-less if the OpenShift registry docker/distribution endpoint included a pointer to the API master. Is that likely to happen soon enough that we won’t need this configuration?

**Comment by aweiteka** [comment]
> Is that likely to happen soon enough that we won’t need this configuration?

Hard to say. I'm guessing it will not land in the next ~2 months. Not sure what the priority is on this and which might come first. I'll link an issue here from openshift/origin.

**Comment by aweiteka** [comment]
Closing based on progress here: https://trello.com/c/J20GczKK
