### ISSUE TITLE
Do not reject when destination is remote

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/skopeo#212]
With default policy set to "type: reject" I am unable to "push" an image from docker-daemon to docker. This is unexpected. I want to protect my host to reject yet that should not prevent me from pushing from docker-daemon. Is there a way to configure policy to accept all from source type docker-daemon with default reject?

**Comment by mtrmac** [comment]
```json
{
  "default": [{"type":"reject"}],
  "transports": {
    "docker-daemon": {
      "": [{"type":"insecureAcceptAnything"}]
    }
  }
}
```

Yes, this very likely should be the default (_after_ https://github.com/containers/image/pull/79 is merged /  on the integrate-all-the-things branch; a policy with an unknown transport would be rejected.)

**Comment by mtrmac** [comment]
Closing in favor of https://github.com/projectatomic/skopeo/issues/224 .

**Comment by mtrmac** [comment]
Sorry, I thought this is a containers/image PR. Never mind.
