### ISSUE TITLE
Docker daemon host need to be configurable

### ISSUE THREAD

**Issue by hustcat** [projectatomic/skopeo#244]
Docker [daemon host](https://github.com/projectatomic/skopeo/blob/master/vendor/github.com/containers/image/docker/daemon/daemon_dest.go#L37) can't be configurable.

**Comment by jlsalmon** [comment]
Is this possible yet?

**Comment by rhatdan** [comment]
It should be able to be.  Reopen if your use fails.

**Comment by jlsalmon** [comment]
I would reopen but I'm not the author.

`skopeo copy` doesn't seem to honour `DOCKER_HOST`:

```
$ echo $DOCKER_HOST
tcp://myhost.local:2375
$ skopeo copy docker://busybox:latest docker-daemon:busybox:latest
Getting image source signatures
Copying blob sha256:d070b8ef96fc4f2d92ff520a4fe55594e362b4e1076a32bbfeb261dc03322910
 0 B / 706.17 KB [-------------------------------------------------------------]
FATA[0006] Error writing blob: Error saving image to docker engine: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

Maybe I'm missing something?

**Comment by rhatdan** [comment]
@mtrmac @runcom Any ideas?

**Comment by mtrmac** [comment]
There is https://github.com/containers/image/pull/328 , designed so that the caller must intentionally opt in into a different configuration, instead of silently changing behavior depending on the environment.

`skopeo` does not currently expose this configuration (`types.SystemContext.DockerDaemon{Host,CertPath}`) via the CLI.

**Comment by jlsalmon** [comment]
Thanks guys. Would I then be correct in saying that it would be a fairly simple addition to the skopeo CLI?

**Comment by rhatdan** [comment]
Sure, open a PR, l

**Comment by jlsalmon** [comment]
I had a quick shot at this in #487
