### ISSUE TITLE
Support cert-based client-server authentication

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/skopeo#250]
Per https://docs.docker.com/engine/security/certificates/

This is being used by Red Hat to provide images only to customers with a valid entitlement subscription.

**Comment by runcom** [comment]
I'm currently working on this on the docker side, this will/should be integrated as part of https://github.com/projectatomic/skopeo/pull/249

**Comment by runcom** [comment]
skopeo does have `--cert-path` and does not auto-read from `/etc/docker/certs.d` - I wouldn't even rely on docker being installed. Can we have a RH package which installs the certificates somewhere on the system (not /etc/docker/certs.d) and tooling which uses skopeo can use the flag to reference the certs?

**Comment by rhatdan** [comment]
What package provides the certs now?  Aren't these just copied from somewhere under /etc/pki?

**Comment by runcom** [comment]
just tested this one, skopeo is indeed already able to pull with cert client auth (given you provide the correct certs, you can see I renamed some `*.cert/*.key` pair to `cert.pem` and `key.pem` to make it work)
```sh
[root@rhel registry.access.redhat.com]# ll
total 256
-rw-r--r--. 1 root root 82975 Nov 17 05:56 2628204870004826799.cert
-rw-------. 1 root root  1679 Nov 17 05:56 2628204870004826799.key
-rw-r--r--. 1 root root 18174 Nov 17 05:56 4571932462082167699.cert
-rw-------. 1 root root  1679 Nov 17 05:56 4571932462082167699.key
-rw-r--r--. 1 root root 82934 Nov 17 05:56 5350127431903172807.cert
-rw-------. 1 root root  1679 Nov 17 05:56 5350127431903172807.key
-rw-r--r--. 1 root root 23861 Nov 17 05:56 8878027713383694498.cert
-rw-------. 1 root root  1679 Nov 17 05:56 8878027713383694498.key
-rw-r--r--. 1 root root 23861 Nov 17 05:58 cert.pem
-rw-------. 1 root root  1679 Nov 17 05:58 key.pem
[root@rhel registry.access.redhat.com]# rm *.pem
rm: remove regular file ‘cert.pem’? y
rm: remove regular file ‘key.pem’? y
[root@rhel registry.access.redhat.com]# cp 5350127431903172807.cert cert.pem
[root@rhel registry.access.redhat.com]# cp 5350127431903172807.key key.pem
[root@rhel registry.access.redhat.com]# skopeo --cert-path=/etc/docker/certs.d/registry.access.redhat.com/ inspect --raw docker://registry.access.redhat.com/rhmap4/mongodb
{
   "schemaVersion": 1,
   "name": "rhmap4/mongodb",
   "tag": "latest",
   "architecture": "amd64",
   "fsLayers": [
      {
         "blobSum": "sha256:8d8d74f9c56b61579becba76e42a9cc598c09241fa0b6a40b2fc2d15ef6067ae"
      },
      {
         "blobSum": "sha256:b1bcd16987754428032e0650ce6caa37e4e54d3c3d2705bd63cafad0a7be895c"
      },
      {
         "blobSum": "sha256:f075d88cadb6e82d374f1dd04ca9e6e44a24bbb524cf5b235e92bffca89c04fa"
      }
   ],
   "history": [
      {
[omitted]
```

**Comment by aweiteka** [comment]
> What package provides the certs now? Aren't these just copied from somewhere under /etc/pki?

@rhatdan I think we should consider extending **/usr/libexec/rhsmcertd-worker** (see `man rhsmcertd`, [upstream source](https://github.com/candlepin/subscription-manager/blob/master/src/daemons/rhsmcertd-worker.py)). 

cc @alikins

**Comment by rhatdan** [comment]
SGTM

**Comment by mtrmac** [comment]
Is there anything that needs to be changed in `skopeo`?

**Comment by runcom** [comment]
I don't think so, let's close and re-open only if I'm wrong :)

**Comment by abdennour** [comment]
i confirm that if your ca.crt files are in /etc/docker/certs.d/<registry>/, then skopeo will read it out-of-the-box without the need to use neither --src-cert-dir nor --dest-cert-dir . i.e.: 

`alias skopeo='docker run --rm -it -v /etc/docker/certs.d:/etc/docker/certs.d:ro quay.io/skopeo/stable:latest'`
