### ISSUE TITLE
Broken master CI

### ISSUE THREAD

**Issue by runcom** [projectatomic/skopeo#27]
@mtrmac #24 broke master CI, we should look into it

**Comment by mtrmac** [comment]
https://travis-ci.org/projectatomic/skopeo/builds/118111300 apparently failed because of
```
Broadcast message from root@testing-gce-62837a88-d47b-4070-8588-9fddab31a890

	(unknown) at 23:04 ...

The system is going down for power off NOW!
```

Is there a way to rerun the test in Travis?

**Comment by runcom** [comment]
not sure, I'm about to merge and we'll see if it's fixed
