### ISSUE TITLE
`skopeo cp` does not properly support Docker Registry v2-1

### ISSUE THREAD

**Issue by jzelinskie** [projectatomic/skopeo#290]
In the Docker Registry protocol v2-1, there is namespace and tag metadata in the manifest. These values need to be rewritten when `skopeo cp` is pushing the manifest to another repository.

I noticed this bug when someone pointed out that `skopeo cp` does not work with Quay.io

**Comment by runcom** [comment]
@mtrmac could be a bug in the rewrite routines?

**Comment by mtrmac** [comment]
Yes, this is https://github.com/containers/image/issues/51 / https://github.com/containers/image/pull/88 . The main outstanding work is reworking quite a few integration tests in skopeo not to depend on this bug.

**Comment by jonboulle** [comment]
Note this isn't really fixed as neither pushing nor pulling works from master:
```
; skopeo copy oci:etcd:latest docker://quay.io/jonboulle/etcd:latest
Getting image source signatures
<...>
Writing manifest to image destination
FATA[0046] Uploading manifest failed, attempted the following formats: application/vnd.docker.distribution.manifest.v2+json(Error writing manifest: Error uploading manifest to /v2/jonboulle/etcd/manifests/latest: manifest invalid: manifest invalid), application/vnd.docker.distribution.manifest.v1+prettyjws(Error creating an updated image manifest: Conversion of image manifest from application/vnd.oci.image.manifest.v1+json to application/vnd.docker.distribution.manifest.v1+prettyjws is not implemented), application/vnd.docker.distribution.manifest.v1+json(Error creating an updated image manifest: Conversion of image manifest from application/vnd.oci.image.manifest.v1+json to application/vnd.docker.distribution.manifest.v1+json is not implemented) 
; 
; 
; skopeo copy docker://quay.io/coreos/etcd:latest oci:etcd:latest
Getting image source signatures
<...>
FATA[0003] Error creating an updated image manifest: Conversion of image manifest from application/vnd.docker.distribution.manifest.v1+prettyjws to application/vnd.oci.image.manifest.v1+json is not implemented 
; 
```

posted containers/image#380 to fix pulling at least.

**Comment by mtrmac** [comment]
@jonboulle The original issue was about being able to correctly push existing schema1 images _at all_. 

Conversions between OCI and schema1 are useful as well, but mostly orthogonal.

**Comment by jonboulle** [comment]
@mtrmac fair enough, I shouldn't have used the OCI example as that is indeed about conversion - but even without that, Quay doesn't work as a dest - apparently now because it returns a 202 on the manifest push. Want me to file a separate issue?
```
FATA[0011] Uploading manifest failed, attempted the following formats: application/vnd.docker.distribution.manifest.v2+json(Error writing manifest: Error uploading manifest to /v2/jonboulle/busybox/manifests/latest: manifest invalid: manifest invalid), application/vnd.docker.distribution.manifest.v1+prettyjws(Error writing manifest: Error uploading manifest to /v2/jonboulle/busybox/manifests/latest: received unexpected HTTP status: 202 ACCEPTED), application/vnd.docker.distribution.manifest.v1+json(Error writing manifest: Error uploading manifest to /v2/jonboulle/busybox/manifests/latest: received unexpected HTTP status: 202 ACCEPTED) 
```

**Comment by mtrmac** [comment]
@jonboulle Interesting, that seems to violate https://github.com/docker/distribution/blob/master/docs/spec/api.md#put-manifest .  Yes, please file that as a separate issue.
