### ISSUE TITLE
No longer builds on OSX

### ISSUE THREAD

**Issue by so0k** [projectatomic/skopeo#310]
```bash
$ make binary-local
go build -ldflags "-X main.gitCommit=b08008c5b21ec869f40f8eb2a6f2e8687984bf95" -gcflags "" -tags "btrfs_noversion libdm_no_deferred_remove" -o skopeo ./cmd/skopeo
# github.com/projectatomic/skopeo/vendor/github.com/containers/storage/storage
vendor/github.com/containers/storage/storage/lockfile.go:136: st.Mtim undefined (type syscall.Stat_t has no field or method Mtim)
vendor/github.com/containers/storage/storage/lockfile.go:136: not enough arguments in call to time.Unix
make: *** [binary-local] Error 2
```

My fork from Oct 21, 2016 still works

```
git clone git@github.com:so0k/skopeo.git
git checkout add-osx-instructions
brew install gpgme
make binary-local
```

**Comment by mtrmac** [comment]
Thanks for your report.

@nalind , any idea?

**Comment by nalind** [comment]
This looks like something https://github.com/containers/storage/pull/11 aims to fix.  @so0k any chance you can try pulling that branch (I've just rebased it) into your checkout and seeing if that helps?  The storage package should be fine, but I don't have the other native libraries wants to link against here, so I can't say 100% that it'll resolve this.

**Comment by huntc** [comment]
Unfortunately the same for me - any progress? Thanks.

**Comment by so0k** [comment]
I'm using my fork for now, didn't have time to try out the suggested fix yet

**Comment by mtrmac** [comment]
https://github.com/containers/storage/pull/11 has now been merged upstream.

macOS users, please test whether https://github.com/projectatomic/skopeo/pull/331 makes it possible to build skopeo again.

**Comment by mtrmac** [comment]
Per https://github.com/containers/image/issues/268#issuecomment-301072144 , assuming that #331 has fixed this; if not, please do reopen this issue or file a new one for the new build failures.
