### ISSUE TITLE
tar input support

### ISSUE THREAD

**Issue by gilligan** [projectatomic/skopeo#323]
The README.md states

> support output to docker load tar(s)

Does this also imply tar files as input? I currently have a .tar that I could load via `docker load` that I would like to push with skopeo but if I understand correctly, I would currently have to unpack it first ?

**Comment by gilligan** [comment]
I just realized that the problem with that is that these tar files do not have a manifest.json and  skopeo cannot add one. I could only get one by loading into docker first but that is the very thing that I am trying to avoid in the first place.

Any suggestions?

**Comment by mtrmac** [comment]
Support for tar file input/output is being worked on in https://github.com/containers/image/pull/148 , and is very close to done. Help on that would be welcome.

I’m afraid until that, or something like that, is merged, there’s not really much that can be done with skopeo as it currently exists.

(BTW skopeo, or containers/image, is already generating a manifest.json when importing from the daemon. That part already exists, but it is not available stand-alone.)

**Comment by gilligan** [comment]
@mtrmac great news. I am using nixos to create a docker image tar file and I would love to be able to use skopeo instead of having to go through docker first :)

Should I close the issue or should we leave it open until support has actually been merged?

**Comment by mtrmac** [comment]
Let’s keep it open as a reminder within the skopeo project.

**Comment by mtrmac** [comment]
This is available as of #327.
