### ISSUE TITLE
skopeo fails to load dev mapper library in Fedora 25.

### ISSUE THREAD

**Issue by humblec** [projectatomic/skopeo#333]
After source compiling skopeo in f25,
 
~~~
[root@localhost skopeo]# ./skopeo inspect docker://docker.io/gluster/gluster-centos
./skopeo: error while loading shared libraries: libdevmapper.so.1.02.1: cannot open shared object file: No such file or directory
~~~

Version: 
```
device-mapper-libs-1.02.136-3.fc25.x86_64 
```
OS version:
```
# cat /etc/redhat-release 
Fedora release 25 (Twenty Five)
```
Looks like the f25 device mapper lib is `1.02`
```
[root@localhost skopeo]# rpm -ql device-mapper-libs
/usr/lib64/libdevmapper.so.1.02
..
```

**Comment by humblec** [comment]
@runcom any pointers on this ?

**Comment by runcom** [comment]
do you have any of these installed on your system:
```
device-mapper-libs-1.02.136-3.fc25.x86_64
device-mapper-devel-1.02.136-3.fc25.x86_64
device-mapper-1.02.136-3.fc25.x86_64
```
?

**Comment by humblec** [comment]
@runcom as mentioned in the description, I have it.    From error, it looks for ` libdevmapper.so.1.02.1` what I have in my system is `/usr/lib64/libdevmapper.so.1.02`.

**Comment by runcom** [comment]
mmm I've never encountered this issue. let me try to reproduce, how did you build skopeo?

**Comment by humblec** [comment]
@runcom after cloning, make all, make install and then run the skopeo binary in f25.

**Comment by runcom** [comment]
I see, likely make all builds from an ubuntu based dockerfile and shared libraries are broken between ubuntu and fedora. Could you try just using `make binary-local`? it requires you to have dependencies installed on the machine you're compiling on but it ensures it uses libraries from your machine.

**Comment by humblec** [comment]
ok.. then I will do make clean and make binary-local

**Comment by humblec** [comment]
@runcom that works!

**Comment by runcom** [comment]
great, let's close this now :tada:

**Comment by zhangguanzhang** [comment]
make binary DISABLE_CGO=1
