### ISSUE TITLE
copying images between docker daemon and CRI-O

### ISSUE THREAD

**Issue by runcom** [projectatomic/skopeo#334]
I tried this was going to work but apparently there are some issues.
```
[root@fedora cri-o]# skopeo --debug copy docker-daemon:docker.io/centos:centos7 containers-storage:docker.io/centos:centos7
```
The above command fails with https://paste.fedoraproject.org/paste/D~i81tuB8iAkWna60qgz2F5M1UNdIGYhyRLivL9gydE=

@nalind @rhatdan PTAL we need this in order to deploy Openshift Origin with CRI-O

**Comment by mtrmac** [comment]
Both blobs `imported as opqaue data`; is `archive.IsArchive` returning a false negative for the layer tar? (Note that it is uncompressed for a `docker-daemon:` input.)
