### ISSUE TITLE
FATA[0000] invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by nccurry** [projectatomic/skopeo#360]
The following command

`skopeo inspect --creds=<user>:<pass> --tls-verify=false docker://openshift-registry-default.wildcard.com/project/image:latest`

 is returning the error 
`FATA[0000] invalid character '<' looking for beginning of value`

from RHEL 7.3 using skopeo version 0.1.19

**Comment by mtrmac** [comment]
In `--creds=<user>:<pass>`, are there literal `<`/`>` characters? If so, please remove them.

If that’s not it, can you paste the output of `skopeo --debug inspect…`, please?

**Comment by nccurry** [comment]
The debug flag helped me solve the issue.

Thanks!

**Comment by mtrmac** [comment]
So is there a bug in skopeo?

**Comment by nccurry** [comment]
Nope! I was unaware of the --debug flag, and that helped me diagnose the real problem... human error :+1: 

The root cause is likely that the target repository returned html/xml and skopeo was expected JSON.
Hence the wtf is this '<' doing here error. 

Not really an error on skopeo's part, but the error message is somewhat cyrptic.

Thanks for your help!

**Comment by mtrmac** [comment]
Well, up to you whether you think the error message should be improved (in which case it would be helpful to know which exact error path to improve, i.e. the full `--debug` output or possibly identifying the URL or whatever is the source of the data), or whether you think this situation is unlikely enough to be not worth worrying about (if so, please close the ticket).
