### ISSUE TITLE
" no handler for negotiate authentication"

### ISSUE THREAD

**Issue by clcollins** [projectatomic/skopeo#375]
Attempting to interact with a private V2 registry, with creds provided in either a config.json or via command line, I receive:

```
sudo skopeo inspect --creds=username:password docker://private-registry/imagename:tag 
FATA[0000] no handler for negotiate authentication  
```

I'd run into the same error with Docker 1.12 using Fedora 25, and found this:  https://github.com/moby/moby/issues/30276#issuecomment-279368196

That worked around the issue for Docker itself.  Is this the same issue, and is there a workaround for Skopeo?  The thread suggests it's something in the RHEL version of the Docker rpm, so maybe this is something else.

Just taking a guess, I tried `skopeo --insecure-policy ... `,  as well as setting up a policy of type `insecureAcceptAnything` for the docker transport, but both resulted in the same error.  I suspect I may be barking up the wrong tree.

**Comment by runcom** [comment]
@clcollins which skopeo and docker version are you using? please create an issue over at projectatomic/docker if there's an issue with docker though.
For skopeo, can you try a newer release? or even master?

**Comment by clcollins** [comment]
@runcom Thanks for the quick reply.  I was using the skopeo RPM from Fedora:

```
/usr/bin/skopeo -v
skopeo version 0.1.22 commit: c7d5a8c5cd84581154281e12ecb683fd69282041
```
I built from source and tried with that, with the same result:

```
[chris@krang skopeo] $ /usr/bin/skopeo -v
skopeo version 0.1.23-dev commit: 91e801b45115580c0709905719ae14c42f201027
[chris@krang skopeo] $   sudo skopeo inspect  docker://private-repo/my-image:tag
FATA[0000] no handler for negotiate authentication 
```

Our V2 registry is using Kerberos auth, and I do have a config.json in ~/.docker/config.json with the creds stored.

In the webserver logs for the registry, I can see the connection attempt receives a 401 response when using `kopeo inspect` but a `docker pull` works fine using those same creds.

I don't think there's an issue with Docker, unless it's with the V2 registry itself.  With the workaround you provided in the other thread, Docker has been working fine.  I'm not evey 100% sure these are related, other than the same wording in the error.   

I'm happy to provide more info if you need it.

**Comment by mtrmac** [comment]
Yeah, the containers/image client for docker/distribution servers currently doesn’t support Kerberos at all, in any version of the client.

The `--signature-verification=false` option to `docker` works around this by disabling the code which uses containers/image, but no amount of options to containers/image can avoid using that client (other than not using a docker/distribution at all, or changing the authentication scheme).

If you really need Kerberos support, then I’m afraid there’s no workaround currently; the code for that support has to be written.

---

But, are you really _using_ the Kerberos support? From a quick look I can't see that Docker supports `negotiate` either. The `--creds=username:password` argument also suggests that the Kerberos support isn’t actually needed.

In that case it seems to just be fairly trivial problem in `dockerClient.setupRequestAuth`: it always uses the first challenge, whether supported or not, and chokes on an unsupported one; it should instead skip the unsupported ones as long as at least one challenge is supported.

**Comment by clcollins** [comment]
@mtrmac Yes, I'm sorry, I was clouded the issue by mentioning Kerberos.  We're have an Apache server in front of the registry, and are using mod_auth_kerb, which I understand uses basic auth between the client and the apache server.  So from Skopeo's point of view, it should look like basic auth, I think.

My apologies for introducing unnecessary info.

**Comment by mtrmac** [comment]
No, it was actually good to mention Kerberos as a legitimate part of the picture.

To maximize the likelihood that a fix works for you, can you paste the full output of `curl -i https://private-registry/v2/`, please? Feel free to replace the host names and other private information, but keep the structure and syntax intact.

**Comment by clcollins** [comment]
Sure, here's the output of the curl command (w/o creds):
```
$ curl -i https://private-registry/v2/
HTTP/1.1 401 Unauthorized
Date: Mon, 17 Jul 2017 18:30:18 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_auth_kerb/5.4
Docker-Distribution-Api-Version: registry/2.0
WWW-Authenticate: Negotiate
WWW-Authenticate: Basic realm="Kerberos Login"
Content-Length: 381
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
</body></html>
```

**Comment by runcom** [comment]
fixed here https://github.com/containers/image/pull/307

**Comment by clcollins** [comment]
Working beautifully with our use case.  Thanks for the quick turnaround!

**Comment by rhatdan** [comment]
@runcom should we cut a new version?

**Comment by runcom** [comment]
Very likely, I'll try to cut a new skopeo possibly after dinner

**Comment by runcom** [comment]
will wait for image-spec v1 to land in c/image before releasing :tada:
