### ISSUE TITLE
Building from source fails with macOS

### ISSUE THREAD

**Issue by ahmetb** [projectatomic/skopeo#390]
I cloned the repo set the env variables correctly.

    $ make install

This fails with error:

    make: *** No rule to make target `skopeo', needed by `install-binary'.  Stop.

**Comment by so0k** [comment]
I just did the build from master, no issues:

```bash
brew install gpgme
git clone https://github.com/projectatomic/skopeo $GOPATH/src/github.com/projectatomic/skopeo
cd $GOPATH/src/github.com/projectatomic/skopeo && make binary-local
go get github.com/cpuguy83/go-md2man && go install github.com/cpuguy83/go-md2man
make docs
sudo make install
```

works fine on OSX

**Comment by so0k** [comment]
or even with 0.1.23 and ostree stub:
```
git checkout v0.1.23
make binary-local BUILDTAGS=containers_image_ostree_stub
```

**Comment by ahmetb** [comment]
Got it, I was missing the binary-local target.

Would you consider creating a homebrew formula for this? `make install` sounds like it'll do things on my system I can't remove easily, i.e. via a package manager.

**Comment by rhatdan** [comment]
@ahmetb We really don't know the package manament of a MAC, but would accept patches to do something like 
make package

Or something which would end up making a installable package for the distro that you ran it on.

**Comment by ahmetb** [comment]
These resources can help:

- tool: https://jkawamoto.github.io/fgo/
- example formula: https://github.com/Homebrew/legacy-homebrew/blob/3c6951ca3072c76af19d096e1332c31de07426c6/Library/Formula/termshare.rb
- more links: https://stackoverflow.com/questions/27097005/how-to-package-go-project-for-homebrew

**Comment by rhatdan** [comment]
Sadly, (Really happily) I only have Linux systems to work on.  :^)

**Comment by so0k** [comment]
I might have a go at it, but priority is very low for me as the Makefiles work fine

**Comment by bcg62** [comment]
homebrew package https://github.com/Homebrew/homebrew-core/pull/29982

**Comment by mtrmac** [comment]
> homebrew package Homebrew/homebrew-core#29982

Great, thanks! (FWIW there has already been a 0.1.30 tagged, apparently we have mismanaged the GitHub options for that. Marked as a release now, at least.)

**Comment by bcg62** [comment]
@mtrmac thanks, updated to 0.1.30
