### ISSUE TITLE
Would be real nice if we had bash completions for this.

### ISSUE THREAD

**Issue by rhatdan** [projectatomic/skopeo#4]

**Comment by runcom** [comment]
easy done with the library skopeo is using to implement a CLI, I'll defer this till we have inspect|layer commands

**Comment by rhatdan** [comment]
Sounds good.

**Comment by mtrmac** [comment]
Looked into this a bit when doing the `--help` cleanup, it was more than a 10-minute job.  So, sharing WIP #154 merely as a starting point, open to anyone finishing it or taking it over.

**Comment by mikebrow** [comment]
here to help.. I'll finish it

**Comment by runcom** [comment]
We have it now https://github.com/projectatomic/skopeo/tree/master/completions/bash
