### ISSUE TITLE
RH V2 support

### ISSUE THREAD

**Issue by runcom** [projectatomic/skopeo#40]
Currently RH registry doesn't support V2 APIs and `skopeo` does not support V1 APIs either:
```
$ ./skopeo inspect docker://registry.access.redhat.com/rhel7 
FATA[0001] error pinging repository, response code 404
```
In order for `skopeo` to work correctly the following APIs should be supported in the RH registry:
```
GET /v2/
GET /v2/<name>/tags/list
GET /v2/<name>/manifests/<reference>
GET /v2/<name>/blobs/<digest>
```
More on each of the above https://docs.docker.com/registry/spec/api/

**Comment by mtrmac** [comment]
… and we will need to figure out a signing story.  Will the RH registry expose OpenShift-like APIs for this, or does this mean defining and implementing another transport mechanism?

**Comment by rhatdan** [comment]
I would think so yes, we only want to have one set of APIs, Whether you can push is one thing, but we need to be able to pull the signature via Crane.

**Comment by twaugh** [comment]
Since registry.access.redhat.com now supports v2, I think we can close this.

In any case it makes little sense for skopeo to support v1 when it does not make guarantees about content addressability -- signing doesn't really make sense there.

**Comment by runcom** [comment]
Agreed, we can always reopen in case we'll ever going to need v1
