### ISSUE TITLE
docker transport support for repositories without a latest tag

### ISSUE THREAD

**Issue by trapier** [projectatomic/skopeo#400]
### Version Affected
`skopeo-0.1.23-2.git1bbd87f.fc26.x86_64`

### Observed Behavior
```
skopeo inspect docker://docker/ucp-etcd
FATA[0001] manifest unknown: manifest unknown   
```

### Expected Behavior
Output similar to a repo with a `latest` tag.

**Comment by runcom** [comment]
This can't be done, how is skopeo supposed to know which tag you're looking for? Sadly, this is docker naming semantic and we can't just choose "the first tag in the tags list".

**Comment by mtrmac** [comment]
Well, there actually is a `/v2/$repo/tags/list` endpoint, but that won’t list untagged images, and as you say, just picking the first tag and showing the details of that image isn’t likely to be useful.

Primarily, `skopeo inspect` inspects an _image_, not a _repository_ (although it does list all the tags in a docker/distribution repo, but that’s an irregular exception, not a clean part of the design).

Perhaps we might end up teaching containers/image, and skopeo, about image repositories (mainly to deal with the tar archive format), but that’s something for the unforeseeable future.

**Comment by trapier** [comment]
Am quite fond of skopeo's tag-listing side effect.   Thanks for the consideration and education.
