### ISSUE TITLE
Using 'skopeo copy' to a registry that requires aws credentials return 403

### ISSUE THREAD

**Issue by mickey-stratoscale** [projectatomic/skopeo#401]
I am trying to use 'skopeo copy' to copy an image from my local registry to a different registry that I can login to using 'aws ecr get-login' command.

After running the login command I get the credentials saved under $HOME/.docker/config.json.

Running this:
docker run -v ~/.docker:/root/.docker:Z --rm --net=host luebken/skopeo  skopeo copy docker://rackattack-nas.dc1:5000/kubernetes-manager:bd6c5759f401652fc938a239b73631756b60879f_kubernetes-manager docker://registry.maestro.stratoscale.com/kubernetes-manager:bd6c5759f401652fc938a239b73631756b60879f_kubernetes-manager

gets me this response:
time="2017-08-27T14:23:27Z" level=fatal msg="Error writing blob: Error initiating layer upload to kubernetes-manager/blobs/uploads/, status 403" 

I entered the container and saw that the the config.json is where it suppose to be and was mounted correctly.

Is there any way I can use 'skopeo copy' using aws ecr credentials?

Thanks!

**Comment by runcom** [comment]
can you actually pull the image using `docker pull` after `docker login`? could you check that? I cannot see anything wrong in what you're doing so I'm wondering credentials are correct at all

**Comment by mickey-stratoscale** [comment]
yes.

im running:
`aws ecr get-login --region <REGION_NAME> --registry-ids <REGISTRY_ID>`

and then run:
docker pull rackattack-nas.dc1:5000/kubernetes-manager:bd6c5759f401652fc938a239b73631756b60879f_kubernetes-manager

and the image is bieng pulled successfully to my computer

**Comment by runcom** [comment]
can you show the `docker login` command as well?

**Comment by mickey-stratoscale** [comment]
I am not using docker login. I am running this command: 
aws ecr get-login --region <REGION_NAME> --registry-ids <REGISTRY_ID> 
inside backticks ``

**Comment by runcom** [comment]
> I am not using docker login. I am running this command:
> aws ecr get-login --region <REGION_NAME> --registry-ids <REGISTRY_ID>
> inside backticks ``

that won't work alone, you still need to `docker login` to save credentials in `~/.docker` - that dir is then mounted _with credentials_ in the container to be used by `skopeo copy`.

As outlined here https://eu-central-1.console.aws.amazon.com/ecs/home?region=eu-central-1#/repositories/create/new you need to `docker login`. Otherwise, your `~/.docker/config.json` won't have credentials for the ecr registry at all.

**Comment by runcom** [comment]
also, make sure you are logged in in the destination repository, in your case `registry.maestro.stratoscale.com` - you need to be logged in there as well otherwise you can't push the image over there :)

So, first make sure you login to both registries (first one is probably optional if it's public) but the destination registry must be logged in in `~/.docker/config.json`.

Can you confirm your `~/.docker/config.json` has `registry.maestro.stratoscale.com`  in it?

**Comment by mickey-stratoscale** [comment]
but I do manage to pull images from the source registry and to push images to the dest registry with those credentials without running docker login in case I don't use skopeo.

So this won't work just in case of using skopeo?

**Comment by runcom** [comment]
> So this won't work just in case of using skopeo?

it depends on what you're doing, It should work and I'm trying to reproduce, but if you can push/pull w/o being docker logged-in either skopeo has a bug or you already have credentials in the docker config. Could you please tell me what I've asked in the previous comments?

**Comment by runcom** [comment]
and afaict you still need to be docker-logged-in, quoting aws docs:

```
To install the AWS CLI and Docker and for more information on the steps below, visit the ECR documentation page.
1) Retrieve the docker login command that you can use to authenticate your Docker client to your registry: 
Note: 
If you receive an "Unknown options: --no-include-email" error, install the latest version of the AWS CLI. Learn more
aws ecr get-login --no-include-email --region eu-central-1

2) Run the docker login command that was returned in the previous step. 
```

**Comment by runcom** [comment]
`aws ecr get-login` won't log your in from docker ...

**Comment by runcom** [comment]
I can confirm you can't push w/o docker login...:
```
The push refers to a repository [redacted.dkr.ecr.eu-central-1.amazonaws.com/runcom]
3a1dff9afffd: Preparing
no basic auth credentials
```
could you please follow my instructions?

**Comment by runcom** [comment]
Just tested, you need to `docker login` first as said. Skopeo will figure out credentials and correctly copy the image to the destination. If you get 403, you aren't logged in and I cannot see how you can push the image with just `aws ecr get-login`, it doesn't store credentials so docker should have failed as well.

```sh
17:10:24 [~/koding/virtbuilders] ‹master› aws ecr get-login --no-include-email --region eu-central-1
docker login -u AWS -p REDACTED https://redacted.dkr.ecr.eu-central-1.amazonaws.com

17:28:30 [~/koding/virtbuilders] ‹master› docker login -u AWS -p REDACTED https://redacted.dkr.ecr.eu-central-1.amazonaws.com
Login Succeeded

17:29:24 [~/koding/virtbuilders] ‹master› skopeo copy docker://alpine docker://redacted.dkr.ecr.eu-central-1.amazonaws.com/runcom
Getting image source signatures
Copying blob sha256:88286f41530e93dffd4b964e1db22ce4939fffa4a4c665dab8591fbab03d4926
 1.90 MB / 1.90 MB [===========================================================]
Copying config sha256:7328f6f8b41890597575cbaadc884e7386ae0acc53b747401ebce5cf0d624560
 1.48 KB / 1.48 KB [===========================================================]
Writing manifest to image destination
Storing signatures
```

**Comment by runcom** [comment]
To recap, make sure you run `docker-login` against source and/or destination if needed. Otherwise nor docker nor skopeo can actually push/pull

**Comment by mickey-stratoscale** [comment]
aws ecr get-login returns a 'docker login' command.
So when I put it inside back ticks(``), it runs it.
I both get 'Login Succeeded' and I see the credentials under the .docker/config.json.

More than this, even when running this:
docker run -v /home/mickey/.docker:/root/.docker:Z -it luebken/skopeo  bash
I see that the config file is indeed exist in the container with the correct credentials.

What am I doing wrong?

**Comment by runcom** [comment]
Can you run skopeo in the container with  --debug flag and paste the output?

**Comment by mickey-stratoscale** [comment]
[root@df2cd12a4ee1 /]# skopeo --debug copy  docker://rackattack-nas.dc1:5000/kubernetes-manager:bd6c5759f401652fc938a239b73631756b60879f_kubernetes-manager_PACKED docker://registry.maestro.stratoscale.com/kubernetes-manager:bd6c5759f401652fc938a239b73631756b60879f_kubernetes-manager_PACKED
DEBU[0000] Ping https://rackattack-nas.dc1:5000/v2/ err <nil> 
DEBU[0000] Ping https://rackattack-nas.dc1:5000/v2/ status 200 
DEBU[0000] GET https://rackattack-nas.dc1:5000/v2/kubernetes-manager/manifests/bd6c5759f401652fc938a239b73631756b60879f_kubernetes-manager_PACKED 
DEBU[0000] Downloading kubernetes-manager/blobs/sha256:257088363f479a8acf66e66f672cbb7c73786b46079c4da68ea1b2d437de15f4 
DEBU[0000] GET https://rackattack-nas.dc1:5000/v2/kubernetes-manager/blobs/sha256:257088363f479a8acf66e66f672cbb7c73786b46079c4da68ea1b2d437de15f4 
DEBU[0000] Checking kubernetes-manager/blobs/sha256:257088363f479a8acf66e66f672cbb7c73786b46079c4da68ea1b2d437de15f4 
DEBU[0000] Ping https://registry.maestro.stratoscale.com/v2/ err <nil> 
DEBU[0000] Ping https://registry.maestro.stratoscale.com/v2/ status 200 
DEBU[0000] HEAD https://registry.maestro.stratoscale.com/v2/kubernetes-manager/blobs/sha256:257088363f479a8acf66e66f672cbb7c73786b46079c4da68ea1b2d437de15f4 
DEBU[0001] ... failed, status 404                       
DEBU[0001] Uploading kubernetes-manager/blobs/uploads/  
DEBU[0001] POST https://registry.maestro.stratoscale.com/v2/kubernetes-manager/blobs/uploads/ 
DEBU[0002] Error initiating layer upload, response http.Response{Status:"403 Forbidden", StatusCode:403, Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Content-Type":[]string{"application/json; charset=utf-8"}, "Content-Length":[]string{"265"}, "Connection":[]string{"keep-alive"}, "Docker-Distribution-Api-Version":[]string{"registry/2.0"}, "Date":[]string{"Mon, 28 Aug 2017 06:58:41 GMT"}}, Body:(*http.cancelTimerBody)(0xc8203d07c0), ContentLength:265, TransferEncoding:[]string(nil), Close:false, Trailer:http.Header(nil), Request:(*http.Request)(0xc8203c68c0), TLS:(*tls.ConnectionState)(0xc820428420)} 
FATA[0002] Error writing blob: Error initiating layer upload to kubernetes-manager/blobs/uploads/, status 403

**Comment by mickey-stratoscale** [comment]
but running a curl command to verify that this actually exists in the source registry returns true:

curl -k https://rackattack-nas.dc1:5000/v2/kubernetes-manager/tags/list | grep bd6c5759f401652fc938a239b73631756b60879f_kubernetes-manager_PACKED

**Comment by runcom** [comment]
Could you check you have `registry.maestro.stratoscale.com` in your config.json? Check both on host and IN the container please

**Comment by mickey-stratoscale** [comment]
registry.maestro is a proxy, my bad, so I reran the same just with the actual registry, result is the same.

Here is what happens when I run it with **docker pull, tag, push** (just renamed here the registry-id):
**docker pull** rackattack-nas.dc1:5000/kubernetes-manager:bd6c5759f401652fc938a239b73631756b60879f_kubernetes-manager_PACKED - **pulls successfully** 

**docker tag** rackattack-nas.dc1:5000/kubernetes-manager:bd6c5759f401652fc938a239b73631756b60879f_kubernetes-manager_PACKED 123.dkr.ecr.us-west-2.amazonaws.com/kubernetes-manager:bd6c5759f401652fc938a239b73631756b60879f_kubernetes-manager_PACKED

**docker push** 123.dkr.ecr.us-west-2.amazonaws.com/kubernetes-manager:bd6c5759f401652fc938a239b73631756b60879f_kubernetes-manager_PACKED - **pushed successfully** 


Here is what happens when I run it using **skopeo** :
docker run -v /home/mickey/.docker:/root/.docker:Z --rm --net=host luebken/skopeo skopeo --debug copy docker://rackattack-nas.dc1:5000/kubernetes-manager:bd6c5759f401652fc938a239b73631756b60879f_kubernetes-manager_PACKED docker://123.dkr.ecr.us-west-2.amazonaws.com/kubernetes-manager:bd6c5759f401652fc938a239b73631756b60879f_kubernetes-manager_PACKED

**output**:
time="2017-08-28T08:52:22Z" level=debug msg="Ping https://rackattack-nas.dc1:5000/v2/ err <nil>" 
time="2017-08-28T08:52:22Z" level=debug msg="Ping https://rackattack-nas.dc1:5000/v2/ status 200" 
time="2017-08-28T08:52:22Z" level=debug msg="GET https://rackattack-nas.dc1:5000/v2/kubernetes-manager/manifests/bd6c5759f401652fc938a239b73631756b60879f_kubernetes-manager_PACKED" 
time="2017-08-28T08:52:22Z" level=debug msg="Downloading kubernetes-manager/blobs/sha256:257088363f479a8acf66e66f672cbb7c73786b46079c4da68ea1b2d437de15f4" 
time="2017-08-28T08:52:22Z" level=debug msg="GET https://rackattack-nas.dc1:5000/v2/kubernetes-manager/blobs/sha256:257088363f479a8acf66e66f672cbb7c73786b46079c4da68ea1b2d437de15f4" 
time="2017-08-28T08:52:22Z" level=debug msg="Checking kubernetes-manager/blobs/sha256:257088363f479a8acf66e66f672cbb7c73786b46079c4da68ea1b2d437de15f4" 
time="2017-08-28T08:52:23Z" level=debug msg="Ping https://123.dkr.ecr.us-west-2.amazonaws.com/v2/ err <nil>" 
time="2017-08-28T08:52:23Z" level=debug msg="Ping https://123.dkr.ecr.us-west-2.amazonaws.com/v2/ status 401" 
time="2017-08-28T08:53:23Z" level=debug msg="Ping http://123.dkr.ecr.us-west-2.amazonaws.com/v2/ err &url.Error{Op:\"Get\", URL:\"http://123.dkr.ecr.us-west-2.amazonaws.com/v2/\", Err:(*http.httpError)(0xc820449a20)}" 
time="2017-08-28T08:53:23Z" level=fatal msg="Error writing blob: Get http://123.dkr.ecr.us-west-2.amazonaws.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"

running cat ~/.docker/config.json on the host and cat /root/.docker/config.json in the container has the same output (replaced the registry-id and the 'auth' part:
{
	"auths": {
		"https://123.dkr.ecr.us-west-2.amazonaws.com": {
			"auth": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==",
			"email": "none"
		}
	}
}

**Comment by runcom** [comment]
@mickey-stratoscale are you using latest skopeo from the master branch? if you're using an older or packaged version please test with master

**Comment by mickey-stratoscale** [comment]
should I checkout to master and build the container? or do you have a built one that I can pull?

**Comment by runcom** [comment]
seems like `luebken/skopeo` is pretty old indeed.....we might have fixed the proxy issue in master cause it's working just fine for me.

> should I checkout to master and build the container? or do you have a built one that I can pull?

Give me 5 minutes to build an image you can use to test with latest master, wait

**Comment by mickey-stratoscale** [comment]
thanks!

**Comment by runcom** [comment]
@mickey-stratoscale I'm pushing the image `runcom/skopeo` (gonna take ~15 minutes). Please re-test with the image `runcom/skopeo` once available - the image you're using is too old, and it's based on Fedora 24 also.

**Comment by runcom** [comment]
`runcom/skopeo` is available https://hub.docker.com/r/runcom/skopeo/ - please test it out

**Comment by mickey-stratoscale** [comment]
will do it now.

**Comment by mickey-stratoscale** [comment]
docker run -v /home/mickey/.docker:/root/.docker:Z --rm --net=host runcom/skopeo skopeo --debug copy docker://rackattack-nas.dc1:5000/kubernetes-manager:bd6c5759f401652fc938a239b73631756b60879f_kubernetes-manager_PACKED docker://123.dkr.ecr.us-west-2.amazonaws.com/kubernetes-manager:bd6c5759f401652fc938a239b73631756b60879f_kubernetes-manager_PACKED

**returns**:
time="2017-08-28T10:41:56Z" level=debug msg="Looking for TLS certificates and private keys in /etc/docker/certs.d/123.dkr.ecr.us-west-2.amazonaws.com" 
time="2017-08-28T10:41:56Z" level=debug msg="Using registries.d directory /etc/containers/registries.d for sigstore configuration" 
time="2017-08-28T10:41:56Z" level=debug msg=" No signature storage configuration found for 123.dkr.ecr.us-west-2.amazonaws.com/kubernetes-manager:bd6c5759f401652fc938a239b73631756b60879f_kubernetes-manager_PACKED" 
time="2017-08-28T10:41:56Z" level=debug msg="Looking for TLS certificates and private keys in /etc/docker/certs.d/rackattack-nas.dc1:5000" 
time="2017-08-28T10:41:56Z" level=debug msg="Using registries.d directory /etc/containers/registries.d for sigstore configuration" 
time="2017-08-28T10:41:56Z" level=debug msg=" No signature storage configuration found for rackattack-nas.dc1:5000/kubernetes-manager:bd6c5759f401652fc938a239b73631756b60879f_kubernetes-manager_PACKED" 
time="2017-08-28T10:41:56Z" level=debug msg="IsRunningImageAllowed for image docker:rackattack-nas.dc1:5000/kubernetes-manager:bd6c5759f401652fc938a239b73631756b60879f_kubernetes-manager_PACKED" 
time="2017-08-28T10:41:56Z" level=debug msg=" Using default policy section" 
time="2017-08-28T10:41:56Z" level=debug msg=" Requirement 0: allowed" 
time="2017-08-28T10:41:56Z" level=debug msg="Overall: allowed" 
time="2017-08-28T10:41:56Z" level=debug msg="GET https://rackattack-nas.dc1:5000/v2/" 
time="2017-08-28T10:41:56Z" level=debug msg="Ping https://rackattack-nas.dc1:5000/v2/ err &url.Error{Op:\"Get\", URL:\"https://rackattack-nas.dc1:5000/v2/\", Err:x509.UnknownAuthorityError{Cert:(*x509.Certificate)(0xc42007db00), hintErr:error(nil), hintCert:(*x509.Certificate)(nil)}}" 
time="2017-08-28T10:41:56Z" level=debug msg="GET https://rackattack-nas.dc1:5000/v1/_ping" 
time="2017-08-28T10:41:56Z" level=debug msg="Ping https://rackattack-nas.dc1:5000/v1/_ping err &url.Error{Op:\"Get\", URL:\"https://rackattack-nas.dc1:5000/v1/_ping\", Err:x509.UnknownAuthorityError{Cert:(*x509.Certificate)(0xc42033e480), hintErr:error(nil), hintCert:(*x509.Certificate)(nil)}}" 
time="2017-08-28T10:41:56Z" level=fatal msg="Error initializing image from source docker://rackattack-nas.dc1:5000/kubernetes-manager:bd6c5759f401652fc938a239b73631756b60879f_kubernetes-manager_PACKED: pinging docker registry returned: Get https://rackattack-nas.dc1:5000/v2/: x509: certificate signed by unknown authority"

**Comment by runcom** [comment]
You need to pass `--tls-verify=false` to skopeo copy to fix that

**Comment by mickey-stratoscale** [comment]
Worked!!
Great tool! Thank you very much for your help!

**Comment by runcom** [comment]
Sure, thanks for the extra testing :)

**Comment by mickey-stratoscale** [comment]
@runcom what is the tag of the container you uploaded for me?

**Comment by runcom** [comment]
`runcom/skopeo:latest`

**Comment by mickey-stratoscale** [comment]
and what version is it now? v0.1.23?

**Comment by runcom** [comment]
Yeah it's v0.1.23 in runcom/skopeo, it's the latest version

**Comment by mickey-stratoscale** [comment]
OK.
Thanks Again
