### ISSUE TITLE
An official release that builds out of the box on macOS again

### ISSUE THREAD

**Issue by copumpkin** [projectatomic/skopeo#418]
I'm running into https://github.com/projectatomic/skopeo/issues/380 and although I can use the workaround in there, but https://github.com/projectatomic/skopeo/pull/382 has a fix for it from a couple of months ago, but it isn't included in any tagged version. Can we get a "release" that builds out of the box on Darwin?

**Comment by mtrmac** [comment]
Yeah, a release should happen soon at least for #416.

Could you also check that #406 works for you, please?

**Comment by mtrmac** [comment]
With 0.1.28:
```console
$ cd ~/Go/src/github.com/projectatomic/
$ mv skopeo skopeo0
$ tar xf ~/t/skopeo-0.1.28.tar.gz 
$ mv skopeo{-0.1.28,}
$ cd skopeo
$ make binary-local
…
$ ./skopeo --override-os linux inspect docker://busybox|head
{
    "Name": "docker.io/library/busybox",
…
```

Building seems to work as documented; please reopen this if that’s not the case.
