### ISSUE TITLE
skopeo Auth method not implemented

### ISSUE THREAD

**Issue by xakraz** [projectatomic/skopeo#428]
Running skopeo against a private Docker registry implemented by JFrog Artifactory does not work

```
skopeo inspect docker://my_private_registry/my/image

time="2017-10-05T15:09:41Z" level=fatal msg="Unimplemented: WWW-Authenticate Bearer replaced by \"basic\"" 

```

Skopeo version: 0.1.14-dev
Artifactory version 4.16.0

What other information should I provide ?

**Comment by mtrmac** [comment]
Please update to a much newer skopeo first, preferably at least the latest release (0.1.23).

The authentication code has been significantly reworked in https://github.com/containers/image/pull/211/files , with a few more fixes since.

**Comment by xakraz** [comment]
Fixed indeed
