### ISSUE TITLE
Not able to copy images from docker storage to containers storage using skopeo when the graph driver is overlay2, kernel version is 3.x

### ISSUE THREAD

**Issue by chaitanyaenr** [projectatomic/skopeo#431]
It fails with the following message:
kernel too old to provide multiple lowers feature for overlay: driver not supported.

version used:
skopeo --version
skopeo version 0.1.24-dev commit: 6ac96b7874815c8fb0ae7eff563942334db5d45d

uname -r
3.10.0-693.el7.x86_64

**Comment by jeremyeder** [comment]
It comes from containers/storage which is vendored into skopeo: https://github.com/containers/storage/blob/master/drivers/overlay/overlay.go#L136

**Comment by mtrmac** [comment]
@nalind ?

**Comment by rhatdan** [comment]
I believe you need to add `override_kernel_check=true to /etc/containers/storage.conf.

**Comment by rhatdan** [comment]
Under storage options.

**Comment by rhatdan** [comment]
We should ship that by default on.  @lsm5

**Comment by chaitanyaenr** [comment]
@rhatdan Thanks, I am able to copy the images after adding the check.

**Comment by rhatdan** [comment]
Skopeo now ships with this on by default.
