### ISSUE TITLE
copy command shouldn't destroy destination on error

### ISSUE THREAD

**Issue by redbaron** [projectatomic/skopeo#448]
good practice is to prepare file on a side and then rename it to destination once done.  Right now skopeo copy leaves destination file in empty state on error

**Comment by runcom** [comment]
Yeah, that's an enhancement we would love to have, are you interested in contributing such a thing? :)

**Comment by mtrmac** [comment]
Which destination transport is this referring to in particular?

FWIW https://github.com/containers/image/pull/288/commits/9e32679d2da77290d095b0630ff0bcd58fbfb8bd implements `atomicallyWriteFile` and `atomicallySymlink`.

**Comment by redbaron** [comment]
Sorry,  for not specifying destination, I am saving images as `docker-archive://`

**Comment by redbaron** [comment]
@mtrmac looks like request should be opened against containers/image, do you want me to close this one?

**Comment by mtrmac** [comment]
Right, containers/image would be a bit better.
