### ISSUE TITLE
How can I export an OCI image to a filesystem?

### ISSUE THREAD

**Issue by BrightEyesBushyTail** [projectatomic/skopeo#467]
Hello!

I am learning to use skopeo - which is very cool, thank you! - and I was wondering how I could use skopeo with a tool like runc. If I have an image in one of the supported repository types, how could I write the resultant (non-layered) filesystem to a folder and fire `runc run` on the result?

I had a look at the `docker-archive` and `dir` transports, but I'm not sure how to unwrap the layers. It also occurred to me that I could bounce an image through docker, mark a container, and `docker export`, but that feels sloppy.

Thanks!

**Comment by runcom** [comment]
@BrightEyesBushyTail you can use umoci to do that - follow the examples here https://github.com/openSUSE/umoci/blob/master/doc/man/umoci-unpack.1.md#example

**Comment by BrightEyesBushyTail** [comment]
Thanks!

**Comment by rhatdan** [comment]
@BrightEyesBushyTail You might want to look at podman, https://github.com/projectatomic/libpod/
Which embeds all of the functionality used by skopeo into a CLI similar to Docker.

```
podman run -ti IMAGE /bin/sh
```
