### ISSUE TITLE
Skopeo copy from private registry tags images incorrectly

### ISSUE THREAD

**Issue by clcollins** [projectatomic/skopeo#472]
When copying an image from a private registry to the docker-daemon transport, Skopeo tags the image as having come from docker.io:

`skopeo copy docker://<private.registry>/testing/testimage:latest docker-daemon:testimage:latest`

Results in:

```
$ docker images | grep testimage
docker.io/testimage                                    latest              560259386a6a        About an hour ago   593 MB
```
I would expect it to either not contain the registry, or have the source registry, not "docker.io".

---
skopeo version 0.1.27 commit: 9d3a3eb447362cc7df192e808bb6a64586af9d3e

**Comment by mtrmac** [comment]
The source and destination specifications in `skopeo copy` are independent; nothing requires the source and destination to have anything in common like the `testimage` name above; `skopeo copy docker://foo docker-daemon:bar` is just as valid. The source could also be something like `dir:$path` which has no associated identity at all.

---

So, regarding the `docker-daemon:` interpretation of `testimage:latest`:

The upstream moby/moby implementation always internally canonicalizes the repository names to mean a specific hostname and repo, i.e. `testimage` is always treated as equivalent to `docker.io/library/testimage`.  The Fedora/RHEL version does have the concept of “unqualified” images which do not contain a host name, but that only happens in some places, and can lead to surprising behavior where in some cases the `docker.io/library/` prefix matters and in some cases it doesn’t, or worse, when a command explicitly using one variant of the name does not actually affect that variant of the name in the backing store.  See https://github.com/containers/image/issues/72 for the full details.

Canonicalizing the `docker-daemon:` name is necessary to obtain the most consistent behavior possible; given that, `docker-daemon:` will not let you to tag the image with an unqualified `testimage`. But if tagging it with `<private.registry>` is acceptable for you, that is possible with something like
```
skopeo copy docker://<private.registry>/testing/testimage:latest docker-daemon:<private.registry>/testing/testimage:latest
```

**Comment by clcollins** [comment]
That makes perfect sense, @mtrmac. Thanks for the explanation.  Tagging the private registry works fine, and should mitigate any confusion regarding the source of the image.

Thanks!
