### ISSUE TITLE
If we are adding new options to skopeo, we need to change to 

### ISSUE THREAD

**Issue by rhatdan** [projectatomic/skopeo#5]
skopeo inspect 
skopeo pull
...

**Comment by runcom** [comment]
@giuseppe already did this copying from runcom/cifetch
the options are

skopeo inspect
skopeo layer <layer><layerN>...

**Comment by rhatdan** [comment]
Super, we need to get this in before we ship fedora 24.

**Comment by runcom** [comment]
doable hopefully, I can let those commands in - given we should still work with @vbatts to unify internal code

**Comment by rhatdan** [comment]
We would obviously need to update atomic command also.

**Comment by runcom** [comment]
work is in WIP here: https://github.com/projectatomic/skopeo/pull/2

**Comment by runcom** [comment]
> Super, we need to get this in before we ship fedora 24.

Just so the Alpha freeze for F24, schedule for F24 is May/June though, I'll fix this asap

**Comment by runcom** [comment]
working here https://github.com/projectatomic/skopeo/pull/8

**Comment by runcom** [comment]
done
