### ISSUE TITLE
question: tool for adding insecure registries

### ISSUE THREAD

**Issue by jfilak** [projectatomic/skopeo#515]
What is the best way to add new insecure registries without the need to manually update the file /etc/containers/registries.conf

I could not google it out.

**Comment by TomSweeneyRedHat** [comment]
Can you make use of:

--registries.d dir use registry configuration files in dir (e.g. for container signature storage), overriding the default path.

and use a different file or are you wanting to specify the insecure registries on the command line itself?

**Comment by mtrmac** [comment]
I’m not aware of any software package for editing the registries configuration; there are readers in Golang (`github.com/containers/image/pkg/sysregistries{,v2}`) and Python (https://github.com/projectatomic/registries ), but neither can update the file.

Of course something I don’t know about may exist.

**Comment by baude** [comment]
The intent has always been to manually edit the file; theoretically something could be created.  Is this being done via automation where manually editing is not feasible ?

**Comment by jfilak** [comment]
> The intent has always been to manually edit the file; theoretically something could be created.

IMHO, the intent in the world of Ansible, Chef, Salt and Puppet was not a good decision.

>  Is this being done via automation where manually editing is not feasible ?

Exactly! I wanted to use sed but the format is so `*` that I would have to use a complicate awk command to achieve my goal.

**Comment by jfilak** [comment]
> --registries.d dir use registry configuration files in dir (e.g. for container signature storage), overriding the default path

Thank you for the suggestion. Unfortunately, I am not sure which command I am supposed to use with the parameter.

I need to start docker service and I need to pull docker images from our internal docker registries. Nothing special - just a VM. But I refuse to configure the VM manually.

**Comment by jfilak** [comment]
What about to define an augeas lens?
http://augeas.net/index.html

**Comment by baude** [comment]
@jfilak i could write up a fairly simple tool for you ... interested in something like that ?

**Comment by jfilak** [comment]
No need to create a tool just for me. I can live with an awk command ;) If you have better things to do, ignore this issue. I will close it when I have the awk command tested.

**Comment by TomSweeneyRedHat** [comment]
Once written, and with your permission, it would probably be handy to drop the tool somewhere in here if you think others could use it.

**Comment by jfilak** [comment]
Here you are:

```bash
awk -v INS_REG="blah" -i inplace -v INPLACE_SUFFIX=.bak 'BEGIN { ins=0; out=1 } /^\[reg.*.ins.*\]$/ { ins=1 } match($0, /^(reg.*= *\[)(\].*)$/, mch) { if (ins==1) { printf "%s'\''%s'\''%s\n", mch[1], INS_REG, mch[2]; ins=0; out=0; } } { if (out==1) print $0; out=1 }' /etc/containers/registries.conf
```

Just replace the value of INS_REG with your insecure registry host name.
Tested with https://github.com/projectatomic/registries/blob/master/registries.conf

It is disgusting and it works only for 'registries = []'. I opened this issue in the hope there is a better way. Perhaps, I can create a PR for https://github.com/projectatomic/registries (I opened the issue here, because `rpm -qf /etc/containers/registries.conf` returned skopeo).

BTW: this can be the solution: https://github.com/hercules-team/augeas/pull/91

**Comment by TomSweeneyRedHat** [comment]
Thanks muchly jfilak

**Comment by TomSweeneyRedHat** [comment]
@jfilak even
