### ISSUE TITLE
skopeo inspect should have a --format command like docker inspect does.

### ISSUE THREAD

**Issue by rhatdan** [projectatomic/skopeo#6]
Would make handling the json easier.

**Comment by runcom** [comment]
I struggle to do this - https://github.com/projectatomic/skopeo#not-todo
I don't see any gain when you could use other tools to do the same...but alright

**Comment by rhatdan** [comment]
No problem, I am fine with that also, although maybe give an example of another tool in man page.

I want to look for the Names label in an image.

**Comment by runcom** [comment]
:+1: :)

**Comment by runcom** [comment]
fixed in master

**Comment by runcom** [comment]
other tools using skopeo can just unmarhal the json output, I added another example in the readme

**Comment by rhatdan** [comment]
Nice.
