### ISSUE TITLE
error: Please use a fully qualified repository name

### ISSUE THREAD

**Issue by dustymabe** [projectatomic/skopeo#66]
skopeo-0.1.11-1.fc23.x86_64

No matter what I do I can only get an error to be output:

```
# skopeo --debug inspect https://docker.io/fedora 
FATA[0000] Please use a fully qualified repository name
```

**Comment by runcom** [comment]
`https://` isn't part of an image reference - drop it off and just use `docker.io/fedora`

**Comment by dustymabe** [comment]
@runcom nothing worked for me. I tried that too:

```
# skopeo --debug inspect docker://docker.io/fedora                                                                                                                                                                        
FATA[0000] Please use a fully qualified repository name
```

```
# skopeo inspect docker.io/fedora
FATA[0000] Please use a fully qualified repository name
```

**Comment by runcom** [comment]
I see, the README.md you're reading is pretty new - refer to https://github.com/projectatomic/skopeo/tree/v0.1.11

**Comment by dustymabe** [comment]
thanks. I'll close this then.

**Comment by dustymabe** [comment]
For the record I did `man skopeo` on my system, which would have given me the correct documentation, but the man page was a template with no contents.

**Comment by runcom** [comment]
@dustymabe right, we added contents to the man page only in master :(
