### ISSUE TITLE
page not found when inspecting RH registry

### ISSUE THREAD

**Issue by runcom** [projectatomic/skopeo#7]
```
$ skopeo registry.access.redhat.com/rhel7 | jq '.Config.Labels.Name'
time="2016-03-08T16:31:20+01:00" level=error msg="Error trying v2 registry: Error parsing HTTP response: invalid character '<' looking for beginning of value: \"<!DOCTYPE HTML PUBLIC \\\"-//W3C//DTD HTML 3.2 Final//EN\\\">\\n<title>404 Not Found</title>\\n<h1>Not Found</h1>\\n<p>The requested URL was not found on the server.</p><p>If you entered the URL manually please check your spelling and try again.</p>\\n\"" 
"rhel7/rhel"
```
command is successful but that debug output is weird and docker.io registry doesn't suffer from this

**Comment by rhatdan** [comment]
This looks like it could be a problem at the registry.access.redhat.com/rhel7.

**Comment by runcom** [comment]
yep, I'll leave this open to track it

**Comment by aweiteka** [comment]
The issue as I understand it is, while the registry technically supports v2 endpoint, the docker client doesn't fall back to v1 images if v2 images are found, so we have to have to land v2 format for all images. It doesn't sound quite right but that was what I understood.

**Comment by twaugh** [comment]
registry.access.redhat.com does not advertise itself as a v2 registry at all right now, i.e. /v2/ will give a 404 response. skopeo needs to fall back to v1 when it sees this.

**Comment by rhatdan** [comment]
When will this change. We don't want to suck in lots of code for skopeo to handle, what is about to be a dead format.

**Comment by runcom** [comment]
Isn't really happening anymore, so closing
