### ISSUE TITLE
spec file out of date?

### ISSUE THREAD

**Issue by cgwalters** [projectatomic/skopeo#80]
Currently skopeo is [under a `freeze`](https://github.com/CentOS/sig-atomic-buildscripts/blob/master/overlay.yml#L73) in [CAHC](https://ci.centos.org/job/atomic-rdgo-centos7/):

Trying to unfreeze, I get:
```
iinstall -m 755 skopeo /builddir/build/BUILDROOT/skopeo-0.1.12.10-0d95328125be9e411b8b4b5f301f2dced5a04d31.5d9911952c34defcf625a69b2ca451345e52e459.el7.centos.x86_64/usr/bin
install: cannot stat 'skopeo': No such file or directory
```

I looked at this briefly but it seems like the actual binary is ending up in some strange place (`WORK=/tmp/go-build43465149` ).

**Comment by mtrmac** [comment]
Yeah, `Makefile` changed like this
```make
-       go build -ldflags "-X main.gitCommit=${GIT_COMMIT}" -o ${DEST}skopeo .
+       go build -ldflags "-X main.gitCommit=${GIT_COMMIT}" -o ${DEST}skopeo ./cmd/skopeo
```

but `skopeo.spec` still contains
```
%gobuild -o skopeo .
```

(I am not sure what `$WORK` has to do with this or why the log above says `iinstall`; nevertheless it seems that `skopeo.spec` does need updating for the cmd/library split.)

**Comment by runcom** [comment]
I'll take care of it, I overlooked the new go build in cmd/skopeo

**Comment by runcom** [comment]
I'm not sure how this went unnoticed when building in Fedora scm (I've also released an update for f23 and f24 but fedpkg build didn't break, weird)

**Comment by cgwalters** [comment]
When this is fixed, can you submit a PR to delete the `freeze:` line to https://github.com/CentOS/sig-atomic-buildscripts ?

**Comment by runcom** [comment]
Sure Colin, will do

**Comment by runcom** [comment]
There seems to be something going on with i686 though when building openshift.go https://kojipkgs.fedoraproject.org//work/tasks/6035/14326035/build.log @mtrmac

**Comment by runcom** [comment]
This command is failing on i686:
```
go build -compiler gc -ldflags ' -B 0x99097609c41c9b2591b3bba5913a65ffe179fbb0' -a -v -x -o skopeo ./cmd/skopeo
```

**Comment by mtrmac** [comment]
```
# github.com/mtrmac/gpgme
In file included from /usr/include/gpgme.h:12:0,
                 from vendor/src/github.com/mtrmac/gpgme/data.go:4:
/usr/include/gpgme-32.h:90:2: error: #error GPGME was compiled with _FILE_OFFSET_BITS = 64, please see the section "Largefile support (LFS)" in the GPGME manual.
 #error GPGME was compiled with _FILE_OFFSET_BITS = 64, please see the section "Largefile support (LFS)" in the GPGME manual.
  ^~~~~
```
