### ISSUE TITLE
Audit handling of digest (non-tag) references

### ISSUE THREAD

**Issue by mtrmac** [projectatomic/skopeo#81]
After `parseDockerImageName`, we treat digests and tags the same. This seems rather suspicious, when the general syntax is `name:tag` but `name@digest`; e.g. the `CanonicalDockerReference` and `IntendedDockerReference` implementations are probably incorrect.

**Comment by runcom** [comment]
Mm could you elaborate?

**Comment by mtrmac** [comment]
AFAICS `IntendedDockerReference` of `docker://busybox@sha256:…` will end up as `busybox:sha256:…` , for example.

**Comment by mtrmac** [comment]
This has long since been cleaned up, `{Intended,Canonical}DockerReference` do not even exist any more.
